# Generated by Django 5.0.7 on 2024-08-05 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=255)),
                (
                    "port",
                    models.CharField(
                        choices=[
                            ("imap.gmail.com", "gmail"),
                            ("imap.yandex.ru", "yandex"),
                            ("imap.mail.ru", "mail"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mail_id", models.PositiveIntegerField()),
                ("subject", models.CharField(max_length=255)),
                ("date_send", models.CharField(max_length=155)),
                ("date_receipt", models.DateField(auto_now_add=True)),
                ("text", models.TextField()),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="mail.emailinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FileMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="")),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="mail.message",
                    ),
                ),
            ],
        ),
    ]
